# Generated by Django 3.0.8 on 2020-08-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='start date')),
                ('end', models.DateField(verbose_name='end date')),
                ('name', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('photo', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=2000)),
                ('type', models.CharField(choices=[('Language', 'Lang'), ('Web/ Framework / App', 'Web'), ('Hard Skills', 'Har')], default='Language', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='start date')),
                ('end', models.DateTimeField(verbose_name='end date')),
                ('place', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
    ]
