# Generated by Django 3.0.8 on 2020-08-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200802_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
