# Generated by Django 3.0.1 on 2020-08-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='start date')),
                ('end', models.DateField(verbose_name='end date')),
                ('name', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('ongoing', models.BooleanField(default=True)),
            ],
        ),
    ]
