# Generated by Django 3.0.1 on 2020-08-25 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalportfolio', '0002_projects_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='image',
        ),
    ]
