# Generated by Django 3.0.1 on 2020-08-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalportfolio', '0004_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='image.jpeg', upload_to='static/finalportfolio/images'),
        ),
    ]
